# Generated by Django 3.2.9 on 2021-11-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='tc_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
